### ISSUE TITLE
applicaton.properties gitignore 처리 해주세요!

### ISSUE THREAD

**Issue by xxxjjhhh** [JoonHyuk0331/CPU_website#1]
applicaton.properties gitignore 처리 해주세요!

공개 리포지토리라서 외부에서 보면 정보 털립니당.

**Comment by JoonHyuk0331** [comment]
좋은지적감사합니다 덕분에 gitignore도 공부함

2024년 1월 24일 (수) 오후 5:20, 김지훈 ***@***.***>님이 작성:
